=== 着想

=== メモ
集合:: `A`
論理クロックを共有する集まり:: `\rm{A}`

=== 2つの場合
まずAとBの2つだけで考えてみる。

[NOTE]
====
これを書いた時点で，私は位相空間についても線形論理についても何も知らない状態。
勉強してからもう一回考えてみると変わりそう。
====

素朴にはAとBの関係は以下のうちどれかである。

. AとBは無関係
. AはBに一方的に影響を及ぼす
. AとBは相互に影響する

まず，「AとBは無関係」の場合を latexmath:[\rm{A} - \rm{A}] と表記することにする。
これは，ある集合 latexmath:[A] と latexmath:[B] が互いに素であることと対応しそう。

次に，「AはBに一方的に影響を及ぼす」場合を， latexmath:[\rm{A} \rightarrow \rm{B}] と表記する事にする。
これは包含関係に対応するのか？ と考えたときに，どちら向きに包含されるのが良さそうかというと，そもそもAとBの定義を考える必要が出てくる。

試しに「内側 → 外側」の場合を考えると，「内側に影響されるならば外側に影響される」に対応する。逆に「外側 → 内側」の場合を考えると，「外側に影響を与えるなら内側に影響を与える」に対応する。
ここで，実際のプログラムが multi-reading には対応できるが multi-writing には対応が難しいことを考えると，前者が良さそう。

ここから，latexmath:[A \subset B] に対応させる。

問題はAとBが相互に影響する部分である。とりあえず latexmath:[\rm{A} \leftrightarrow \rm{B}] としてみる。
これを latexmath:[\rm{A} \rightarrow \rm{B} \land \rm{B} \rightarrow \rm{A}] と考えると，対応する集合は一つに潰れてしまう。
つまりAとBは1つの状態を持つという事に相当する。それでも整合性は取れるのだが，何も言っていないのと同じなので他の方法を考える。

何も言っていないという事について，「それを言い出したら結局は全体で一つの巨大な状態を持てば良い」という結論になってしまうためである。これは latexmath:[A] と latexmath:[B] を latexmath:[A \setminus B] と latexmath:[B \setminus A] と latexmath:[A \intersect B] に分ければ解決するのだろうか？ つまり任意の2つについて直積は少なくとも存在しそう。

NOTE: 考えるべきこととして「この集合の和集合や共通部分が正確には何であるか」などがある。
